global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "findy-services"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "apigateway:8080"
          - "user-service:8889"
          - "shopping-service:8887"
          - "map-service:8888"
          - "recommendation-service:8886"