package com.princesses7.findy.recommendation.chatbot.entity;

public enum ChatIntent {
	GENERAL,
	RECIPE_INGREDIENT_RECOMMENDATION,
	GENERAL_PRODUCT_RECOMMENDATION,
	PRODUCT_SEARCH,
	INVENTORY_INQUIRY,
	PROMOTION_INQUIRY,
	COUPON_INQUIRY
}