server:
  address: 0.0.0.0
  port: 8887

spring:
  application:
    name: shopping-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:findy}?currentSchema=${DB_SCHEMA:shopping_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:shopping_service}
    default-schema: ${DB_SCHEMA:shopping_service}
    create-schemas: true
    table: flyway_schema_history
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:shopping_service}
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

naver:
  shopping:
    base-url: https://openapi.naver.com
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

mfds:
  barcode:
    base-url: https://openapi.foodsafetykorea.go.kr/api
    key-id: ${MFDS_API_KEY}
    service-id: I2570
    data-type: json
  linked-product:
    base-url: https://openapi.foodsafetykorea.go.kr/api
    key-id: ${MFDS_API_KEY}
    service-id: C005
    data-type: json

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-4o-mini

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
