server:
  port: 8885

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:findy}?currentSchema=${DB_SCHEMA:analytics_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:analytics_service}
    default-schema: ${DB_SCHEMA:analytics_service}
    create-schemas: true
    table: flyway_schema_history
    locations: classpath:db/migration

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:analytics_service}
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

analytics:
  source-schema: ${ANALYTICS_SOURCE_SCHEMA:shopping_service}
  user-source-schema: ${ANALYTICS_USER_SOURCE_SCHEMA:user_service}