package com.princesses7.findy.recommendation.recommendation.type;

public enum RecommendationBaseType {

	PREFERENCE_EMBEDDING,
	NO_PREFERENCE_FALLBACK,
	NO_PRODUCT_EMBEDDING_FALLBACK,
	EMPTY_RECOMMENDATION_FALLBACK
	PREFERENCE_ONLY,
	PREFERENCE_WITH_PURCHASE_HISTORY,
	PURCHASE_HISTORY_ONLY,
	POPULAR_FALLBACK,
	NO_PRODUCT_EMBEDDING_FALLBACK
}